### ISSUE TITLE
meta/main.yml file not detected

### ISSUE THREAD

**Issue by ltarasiewicz** [k0st1an/ansible-vsftpd#1]
Hi,

When trying to install the role with `ansible-galaxy`, I'm getting this:

> error: this role does not appear to have a meta/main.yml file.
> k0st1an.vsftpd was NOT installed successfully.

I can see that you included the file with metadata, but it's not being read :/

**Comment by k0st1an** [comment]
Hi,

Fixed issue. Trouble was in old version (v1.0.0).
